PFNGLBLENDFUNCSEPARATEPROC glBlendFuncSeparate = NULL;
PFNGLBLENDEQUATIONSEPARATEPROC glBlendEquationSeparate = NULL;
PFNGLBINDFRAMEBUFFERPROC glBindFramebuffer = NULL;
PFNGLGENFRAMEBUFFERSPROC glGenFramebuffers = NULL;
PFNGLDELETEFRAMEBUFFERSPROC glDeleteFramebuffers = NULL;
PFNGLGENRENDERBUFFERSPROC glGenRenderbuffers = NULL;
PFNGLBINDRENDERBUFFERPROC glBindRenderbuffer = NULL;
PFNGLDELETERENDERBUFFERSPROC glDeleteRenderbuffers = NULL;
PFNGLRENDERBUFFERSTORAGEPROC glRenderbufferStorage = NULL;
PFNGLFRAMEBUFFERRENDERBUFFERPROC glFramebufferRenderbuffer = NULL;
PFNGLFRAMEBUFFERTEXTURE2DPROC glFramebufferTexture2D = NULL;
PFNGLCHECKFRAMEBUFFERSTATUSPROC glCheckFramebufferStatus = NULL;
PFNGLSTENCILOPSEPARATEPROC glStencilFuncSeparate = NULL;
PFNGLSTENCILFUNCSEPARATEPROC glStencilOpSeparate = NULL;

PFNGLACTIVETEXTUREPROC glActiveTexture = NULL;

PFNGLGENBUFFERSPROC glGenBuffers = NULL;
PFNGLBINDBUFFERPROC glBindBuffer = NULL;
PFNGLDELETEBUFFERSPROC glDeleteBuffers = NULL;
PFNGLBUFFERDATAPROC glBufferData = NULL;

PFNGLCLIENTACTIVETEXTUREPROC glClientActiveTexture = NULL;

static bool glInited = false;

#define GET_FUNC_PTR(ptr, type) \
	if(!(ptr = (type) wglGetProcAddress(#ptr))) \
	{	ptr = (type) wglGetProcAddress(#ptr"EXT");	}

void initExtensions()
{
	if(glInited)
		return;

	glInited = true;

	GET_FUNC_PTR(glBlendFuncSeparate, PFNGLBLENDFUNCSEPARATEPROC);
	GET_FUNC_PTR(glBlendEquationSeparate, PFNGLBLENDEQUATIONSEPARATEPROC);
	GET_FUNC_PTR(glBindFramebuffer, PFNGLBINDFRAMEBUFFERPROC);
	GET_FUNC_PTR(glGenFramebuffers, PFNGLGENFRAMEBUFFERSPROC);
	GET_FUNC_PTR(glDeleteFramebuffers, PFNGLDELETEFRAMEBUFFERSPROC);
	GET_FUNC_PTR(glGenRenderbuffers, PFNGLGENRENDERBUFFERSPROC);	
	GET_FUNC_PTR(glBindRenderbuffer, PFNGLBINDRENDERBUFFERPROC);
	GET_FUNC_PTR(glDeleteRenderbuffers, PFNGLDELETERENDERBUFFERSPROC);
	GET_FUNC_PTR(glRenderbufferStorage, PFNGLRENDERBUFFERSTORAGEPROC);
	GET_FUNC_PTR(glFramebufferRenderbuffer, PFNGLFRAMEBUFFERRENDERBUFFERPROC);
	GET_FUNC_PTR(glFramebufferTexture2D, PFNGLFRAMEBUFFERTEXTURE2DPROC);
	GET_FUNC_PTR(glCheckFramebufferStatus, PFNGLCHECKFRAMEBUFFERSTATUSPROC);
	GET_FUNC_PTR(glStencilFuncSeparate, PFNGLSTENCILOPSEPARATEPROC);
	GET_FUNC_PTR(glStencilOpSeparate, PFNGLSTENCILFUNCSEPARATEPROC);

	GET_FUNC_PTR(glActiveTexture, PFNGLACTIVETEXTUREPROC);

	GET_FUNC_PTR(glGenBuffers, PFNGLGENBUFFERSPROC);
	GET_FUNC_PTR(glBindBuffer, PFNGLBINDBUFFERPROC);
	GET_FUNC_PTR(glDeleteBuffers, PFNGLDELETEBUFFERSPROC);
	GET_FUNC_PTR(glBufferData, PFNGLBUFFERDATAPROC);

	GET_FUNC_PTR(glClientActiveTexture, PFNGLCLIENTACTIVETEXTUREPROC);
}

#undef GET_FUNC_PTR
